# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ddongree-bus-app.devcaffeine.net
baseUrl: https://ddongree-bus-app.devcaffeine.net
title: "똥그리버스"
email: caffeine.driven.dev@gmail.com
author: devCaffeine
description: 똥그리버스를 위한 웹 페이지

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
  - title: kakaotalk
